"""Preserve the first draft and apply one recorded editorial pass."""
from pathlib import Path

root=Path(__file__).resolve().parent
text=(root/'first-draft.md').read_text(encoding='utf-8')
edits=[
('A restartable block export can recover correctly by scanning its output, but this repeats work even after a clean finish. We replace the routine scan with two alternating progress slots that name a completed block and are checked against the output at restart. Data synchronization precedes progress recording; the generation is acknowledged only after the progress slot is synchronized. In a constructed 100-block export, clean recovery reads two progress entries and one data-block header instead of inspecting 100 headers. A torn latest slot can cause one block to be replayed, and loss of both valid entries restores the full scan. The design adds one progress-slot synchronization per block. These examples establish a change in restart inspection and replay under the specified crash model, not a measured reduction in restart time or export cost.',
 'The existing block exporter recovers correctly by scanning its output for the longest valid prefix. Two alternating progress slots let restart check a recorded boundary before resorting to that scan. Progress is recorded after the corresponding output data are synchronized and is validated against the named block at restart. In the constructed clean-finish trace, this changes inspection from 100 data headers to two progress entries and one data header. A torn latest slot causes one block to be replayed in another trace; invalidity of both slots restores the full scan. The shortcut costs one additional progress-slot synchronization per block. These teaching examples expose a tradeoff between recording durable progress and inspecting output, without measuring total restart time or export efficiency.'),
('Restart checks both slots and validates the data block named by each otherwise valid entry. Among entries that pass these checks, it chooses the largest generation and resumes after that completed prefix.',
 'Restart checks both progress slots. An entry is usable only if its own checks pass and its named data block validates; recovery selects the largest generation among usable entries and resumes after that completed prefix.'),
('The offset-only comparator skips unwritten output in C2. Its apparent reduction in replay there is therefore not an eligible recovery benefit. By contrast, the existing scanner is safe under the modeled crash behavior. The relevant safe comparison is between its scanning work and the new procedure\'s validated progress, including fallback.',
 'The identical replay counts in C2 and C3 distinguish two recovery decisions. In C2, replay restores block 100 because a returned write did not make it durable. In C3, replay conservatively rewrites a durable block because recovery can validate only the older recorded boundary. The offset-only comparator skips unwritten output in C2, so its apparent avoidance of work is a recovery failure. The safe full scanner, rather than that shortcut, is the relevant baseline for judging inspection cost.'),
('After the clean finish in C1, the new procedure substitutes two progress-entry reads and one named data-header inspection for the 100-header scan. No block is replayed. C2 and C3 have the same new inspection and replay counts, but different reasons for replay: C2 must recover a block that was written without becoming durable, while C3 returns to an older completed generation because the latest progress slot is torn.',
 'After the clean finish in C1, the new procedure substitutes two progress-entry reads and one named data-header inspection for the 100-header scan, with no replay. C2 and C3 retain that inspection count but each replay one block. These are the supplied trace counts, not measurements of elapsed recovery time.'),
('Replay is another component of recovery. The two slots allow a previous generation to remain usable after a torn latest entry, but using that generation can replay a valid block, as C3 demonstrates. Rewriting from the selected prefix avoids appended duplication, conditional on the original deterministic input remaining available. These examples do not establish a general replay bound beyond the supplied traces.',
 'The fallback and replay cases also limit what the extra metadata buys. A preceding slot can remain usable when the latest one tears, but it may identify an older prefix than the valid output would permit. That conservatism requires deterministic input to be available for rewriting. When neither slot validates, the metadata provides no inspection shortcut at all. The four traces do not establish a general replay bound or a failure probability.')]
for old,new in edits:
    assert text.count(old)==1,old[:80]
    text=text.replace(old,new)
(root/'final.md').write_text(text,encoding='utf-8')
print(f'Applied {len(edits)} replacements in one self-edit pass.')
