"""Author the compact report and inspection records from actual transfer outputs."""
from pathlib import Path
import argparse,hashlib,json,difflib,subprocess,sys,os,shutil
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def save(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf-8')
def main():
 p=argparse.ArgumentParser();p.add_argument('--input',type=Path,required=True);p.add_argument('--root',type=Path,required=True);p.add_argument('--paper-skill',type=Path,required=True);p.add_argument('--figure-skill',type=Path,required=True);p.add_argument('--font',type=Path,required=True);p.add_argument('--pdftoppm',type=Path,required=True);a=p.parse_args();o=a.root
 e=json.loads((o/'final-authored/authored-edits.json').read_text(encoding='utf-8'));by={v['paragraph_id']:v for v in e['edits']}
 # Keep report assets next to the output; input and output may be on different drives.
 assets=o/'report-assets';assets.mkdir(exist_ok=True)
 original=assets/'original.png'
 if original.exists():raise ValueError('Report asset already exists; use a new output directory')
 shutil.copy2(a.input/'original.png',original)
 report={'title':'三腔压力夹具：完整图文迁移试用简报','summary':'本次从未使用过的原创 DEMO 输入独立完成英文短稿与 160×85 mm 机制图。主线为：保留原有共同参考测量，把三根参考软管变为一个可更换、需定位并密封的底座。全部结果仍为合成输入。','baseline':'原稿以部件清单和结果概述为主，原图只列四类部件。清稿与本轮黄色审阅稿由同一文字补丁生成，再由正式替图工具写入所选 PNG；源 DOCX 未覆盖。','changes':[
 {'focus':'入口：先让读者看到一次具体的装配改变','before':by['P0006']['before'],'after':' '.join(by['P0006']['after'].split('. ')[:3])+'.','reason':'承认软管式基线已有共同参考，随后明确仍需解决的更换接口问题。','evidence':'source.docx 与 implementation.md：三样品模块不动；三软管被一个可更换底座替代。','limits':'未建立文献首创；新稿不是实物验证。'},
 {'focus':'结果：让时间、泄漏与压力差共同决定解释','before':'Pressure differences are similar in this small constructed set. The pin-free version is faster to assemble but two attempts fail the leak check.','after':'Thus the shorter setup is accompanied by a 0.01 kPa increase in two conditions and no change in the third; it is not a demonstrated accuracy improvement. The two failed attempts cannot be counted as additional usable time savings.','reason':'用实际配对代价替换含混的 similar，并保留失败对可用节时的限制。','evidence':'results.csv 全部 9 行保留；三对时间减少 5.3、5.0、5.3 min；两次 pin-free 失败及 NA 均保留。','limits':'三工况不是随机样本，没有总体显著性或量产可靠性结论。'}],
 'figures':[{'title':'实际图形前后对照（同为 160×85 mm）','before':'report-assets/original.png','after':'final-figure/figure.png','caption':'原图是部件列表。新图用三个封闭隔膜和连续参考空间直接显示隔离与共享的同时成立；橙色断面表示一片带三个口的密封垫。代价：平面剖面需要图注说明密封垫断面，软管基线由正文承担。未选展开候选，因为它削弱了隔膜与参考侧的直接邻接；该候选及首稿仍保留。'}],
 'checks':[{'scope':'数据与对象','status':'技术通过','detail':'final-complete 的原生整表曾完整保留。后续 final-delivery 仅修表头和布局；9条数据行的完整规范化XML、非表正文、图及其他ZIP部件保持一致。整表XML已改变，不冒称完全保留。图像绑定与160×85 mm尺寸另行核对；本稿无原生公式。'}, {'scope':'图形与自修','status':'模型自审已完成','detail':'正常色、灰度和单条件色觉模拟已查看。首次图的密封垫引线穿字，经一次修复后移至外侧；PDF 最小字号 9.45 pt。'}, {'scope':'主编辑者后续页面修复','status':'已执行，待最终页面复验','detail':'主编辑者检查9页后发现第3页代码式长表头断词。随后改为易读英文表头、21/42/25/48/24 mm列宽、10 pt粗体浅底色；这是自修稿之后的版式收尾，不倒写为首次稿已做到。'}],
 'remaining':['真实实验、领域同行评审与作者认可均未发生；不能据此称为 Nature 通用质量或一般迁移能力已证实。','这是候选技能的一次新上下文完整迁移，没有普通模型／旧技能的同期受控比较。','首份完整稿为 first-complete-v1；一次自修稿为 final-complete；当前 final-delivery 只追加主编辑者指出的表头版式修复。最终页面渲染记录另存。'],
 'final_files':['英文清稿：final-delivery/clean.docx；黄色审阅稿：final-delivery/review.docx。','实际入稿图：final-figure/figure.png；图源：final-authored/figure_spec.json；SVG/PDF：final-figure/figure.svg、figure.pdf。','图注：final-authored/caption.txt；替代文字：final-authored/alt_text.txt；表头改动：final-delivery/*-table-receipt.json。']}
 report['figures'][0].update(source_spec='final-authored/figure_spec.json',caption_file='final-authored/caption.txt',embedded_asset='final-figure/figure.png')
 save(o/'editorial-report-final.json',report)
 subprocess.run([sys.executable,str(a.paper_skill/'scripts/build_editorial_report.py'),str(o/'editorial-report-final.json'),str(o/'editorial-report-final.docx')],check=True)
 for label in ['clean','review']:
  binding=json.loads((o/'final-complete'/(label+'-figures.json')).read_text(encoding='utf-8'))
  binding['docx_sha256']=sha(o/'final-delivery'/(label+'.docx'))
  target=o/'final-delivery'/(label+'-figures.json');save(target,binding)
  subprocess.run([sys.executable,str(a.paper_skill/'scripts/audit_figure_integration.py'),str(o/'final-delivery'/(label+'.docx')),str(target),'--parent',str(a.input/'source.docx'),'--out',str(o/'final-delivery'/(label+'-integration-audit.json'))],check=True)
 before=(o/'first-authored-complete/source-prose.txt').read_text(encoding='utf-8').splitlines(True);after=(o/'final-text/clean.txt').read_text(encoding='utf-8').splitlines(True)
 (o/'prose-delivery.patch').write_text(''.join(difflib.unified_diff(before,after,fromfile='input/source.docx visible body prose',tofile='final-delivery/clean.docx visible body prose; header edits recorded separately')),encoding='utf-8')
 files=[a.input/n for n in ['source.docx','implementation.md','results.csv','README.md','original.png']]
 prefs=['SKILL.md','references/reviewer-method.md','references/dependencies.md','references/presentation-review.md','references/integrated-delivery.md','references/story-and-main-figure.md','references/object-illustration.md','examples/heat-story/README.md','examples/heat-story/manuscript.md','scripts/apply_authored_edits.py','scripts/review_docx.py','scripts/apply_figure_edits.py','scripts/audit_figure_integration.py','scripts/audit_preservation.py','scripts/build_editorial_report.py']
 frefs=['SKILL.md','references/workflow.md','references/quality-and-acceptance.md','references/dependencies.md','references/visual-explanation.md','references/drawing-and-depth.md','references/design-exploration.md','references/existing-svg-review.md','references/semantic-constraints.md','references/figure-spec.md','templates/figure_spec.json','scripts/render_figure.py','scripts/figure_core.py','scripts/palette_tools.py','scripts/check_figure.py','scripts/semantic_audit.py','scripts/probe_runtime.py','assets/reference_palettes.json','vendor/nature-figure/audit_pdf_text.py']
 files += [a.paper_skill/n for n in prefs]+[a.figure_skill/n for n in frefs]+[a.font,a.pdftoppm]
 save(o/'loaded-source-files-delivery.json',{'scope':'Input, guidance provenance and tool/font hashes at this fixed rebuild. This receipt does not imply another model read or a new independent generation. Standard-library/site-package files are not expanded.','loading':'Actual CLI-selected tool files; exact user-level version is the hashed SKILL.md. Original fresh-context receipt remains separate.','files':[{'path':str(x.resolve()),'sha256':sha(x),'bytes':x.stat().st_size} for x in files]})
 save(o/'figure-review.json',{'figure_sha256':sha(o/'final-figure/figure.png'),'svg_sha256':sha(o/'final-figure/figure.svg'),'reviewer':'generating model self-review','technical_status':'PASS (see final-figure/qa.json and integration receipts)','scientific_review_status':'SELF_REVIEW_ONLY','visual_review_status':'SELF_REVIEW_COMPLETE','author_acceptance':False,'views_seen':['normal PNG','grayscale PNG','deuteranopia PNG'],'observations':['Three sample spaces terminate at closed dark diaphragm boundaries.','One unpartitioned reference cavity reaches all three reference sides.','Two pin bodies are visible outside the three modules.','One gasket uses cut segments; this sectional convention is explicitly explained in caption.','The repaired gasket leader no longer crosses the reference label.','Grayscale preserves topology and labels without relying on blue/green hue distinctions.'],'limits':['No actual mechanical dimensions or membrane deflection','Schematic pressure relationship, not a fabrication drawing','No perspective or photorealistic quality claim','Word page review recorded separately by lead editor']})
 save(o/'delivery-receipt.json',{'task':'Fixed artefacts of a candidate-only fresh-context complete DEMO transfer plus a subsequent lead-editor page repair','input_sha256':sha(a.input/'source.docx'),'first_complete':{'clean':sha(o/'first-complete-v1/clean.docx'),'review':sha(o/'first-complete-v1/review.docx'),'figure':sha(o/'first-figure/figure.png')},'self_repaired':{'clean':sha(o/'final-complete/clean.docx'),'review':sha(o/'final-complete/review.docx'),'figure':sha(o/'final-figure/figure.png')},'final_delivery':{'clean':sha(o/'final-delivery/clean.docx'),'review':sha(o/'final-delivery/review.docx'),'figure':sha(o/'final-figure/figure.png')},'self_review_passes':1,'subsequent_page_repair':'Lead editor found long code-style table header; replaced only known header labels and table/header layout, preserving all nine data-row XML elements and all science/figure content.','content_boundary':'All input numbers are DEMO; no new data, citations, statistical significance, physical validation or human acceptance.'})
 print(json.dumps({'report':str(o/'editorial-report-final.docx'),'records':'written'},ensure_ascii=False))
if __name__=='__main__':main()
